"""Initial schema — 11 tables

Revision ID: 46105259c147
Revises: 
Create Date: 2026-05-25 16:50:14.308937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46105259c147'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('raw_text_length', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sections_studied', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('score_pct', sa.Float(), nullable=False),
    sa.Column('difficulty_level', sa.String(length=16), nullable=False),
    sa.Column('is_cold_start', sa.Boolean(), nullable=False),
    sa.Column('adaptive_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("difficulty_level IN ('easy', 'medium', 'hard')", name='ck_sessions_difficulty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_completed_at', 'sessions', ['completed_at'], unique=False)
    op.create_index('ix_sessions_started_at', 'sessions', ['started_at'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('importance', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("importance IN ('critical', 'normal', 'minor')", name='ck_topics_importance'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_topics_category', 'topics', ['category'], unique=False)
    op.create_index('ix_topics_slug', 'topics', ['slug'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('sub_section_id', sa.String(length=64), nullable=False),
    sa.Column('sub_section_title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('has_table', sa.Boolean(), nullable=False),
    sa.Column('has_bullets', sa.Boolean(), nullable=False),
    sa.Column('chunk_kind', sa.String(length=32), nullable=False),
    sa.Column('cross_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("chunk_kind IN ('narrative', 'glossary_entry', 'split')", name='ck_chunks_chunk_kind'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunks_section_id', 'chunks', ['section_id'], unique=False)
    op.create_index('ix_chunks_sub_section_id', 'chunks', ['sub_section_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('source_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('choice_a', sa.Text(), nullable=False),
    sa.Column('choice_b', sa.Text(), nullable=False),
    sa.Column('choice_c', sa.Text(), nullable=False),
    sa.Column('choice_d', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("correct_answer IN ('A', 'B', 'C', 'D')", name='ck_questions_correct_answer'),
    sa.CheckConstraint("difficulty IN ('easy', 'medium', 'hard')", name='ck_questions_difficulty'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questions_section_id', 'questions', ['section_id'], unique=False)
    op.create_index('ix_questions_session_id', 'questions', ['session_id'], unique=False)
    op.create_table('section_topic_mastery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('times_asked', sa.Integer(), nullable=False),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('times_wrong', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'topic_id', name='uq_section_topic_mastery')
    )
    op.create_index('ix_section_topic_mastery_weight', 'section_topic_mastery', ['weight'], unique=False)
    op.create_table('section_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('depth', sa.String(length=16), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.CheckConstraint("depth IN ('primary', 'secondary', 'mention')", name='ck_section_topics_depth'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'topic_id', name='uq_section_topics')
    )
    op.create_index('ix_section_topics_topic_id', 'section_topics', ['topic_id'], unique=False)
    op.create_table('topic_mastery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('times_asked', sa.Integer(), nullable=False),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('times_wrong', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_mastered', sa.Boolean(), nullable=False),
    sa.Column('last_asked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_wrong_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id')
    )
    op.create_index('ix_topic_mastery_is_mastered', 'topic_mastery', ['is_mastered'], unique=False)
    op.create_index('ix_topic_mastery_weight', 'topic_mastery', ['weight'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.String(length=1), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("user_answer IN ('A', 'B', 'C', 'D')", name='ck_answers_user_answer'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_index('ix_answers_is_correct', 'answers', ['is_correct'], unique=False)
    op.create_table('chunk_topics',
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id', 'topic_id')
    )
    op.create_index('ix_chunk_topics_topic_id', 'chunk_topics', ['topic_id'], unique=False)
    op.create_table('question_topics',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'topic_id')
    )
    op.create_index('ix_question_topics_topic_id', 'question_topics', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_question_topics_topic_id', table_name='question_topics')
    op.drop_table('question_topics')
    op.drop_index('ix_chunk_topics_topic_id', table_name='chunk_topics')
    op.drop_table('chunk_topics')
    op.drop_index('ix_answers_is_correct', table_name='answers')
    op.drop_table('answers')
    op.drop_index('ix_topic_mastery_weight', table_name='topic_mastery')
    op.drop_index('ix_topic_mastery_is_mastered', table_name='topic_mastery')
    op.drop_table('topic_mastery')
    op.drop_index('ix_section_topics_topic_id', table_name='section_topics')
    op.drop_table('section_topics')
    op.drop_index('ix_section_topic_mastery_weight', table_name='section_topic_mastery')
    op.drop_table('section_topic_mastery')
    op.drop_index('ix_questions_session_id', table_name='questions')
    op.drop_index('ix_questions_section_id', table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_chunks_sub_section_id', table_name='chunks')
    op.drop_index('ix_chunks_section_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_topics_slug', table_name='topics')
    op.drop_index('ix_topics_category', table_name='topics')
    op.drop_table('topics')
    op.drop_index('ix_sessions_started_at', table_name='sessions')
    op.drop_index('ix_sessions_completed_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('sections')
    # ### end Alembic commands ###
